name: PR Conventional Commit Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enforce Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            ci
            build
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close PR if not Conventional
        if: failure()
        run: gh pr close ${{ github.event.pull_request.number }} -r "Your PR does not follow Conventional Commits!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
