name: PR Conventional Commit Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enforce Conventional Commits on PR Title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            ci
            build
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Enforce Conventional Commits on Commit Messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Close PR if Not Conventional
        if: failure()
        run: gh pr close ${{ github.event.pull_request.number }} --comment "Your PR does not follow Conventional Commits!"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Send Email Notification on PR Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "PR Rejected - Invalid Commit Message"
          body: "Your Pull Request #${{ github.event.pull_request.number }} was rejected because it does not follow Conventional Commits."
          to: ${{ secrets.MAIL_USERNAME }}
          from: "GitHub Actions <${{ secrets.MAIL_FROM }}>"
